#!/usr/bin/env bash
#
# Utility to make log files from multi-node tests easier to analyze.
# Replaces jvm names and host:port with corresponding logical role name.
#


# check for an sbt command
type -P sbt &> /dev/null || fail "sbt command not found"

sbt "project akka-remote-tests" "test:run-main akka.remote.testkit.LogRoleReplace $1 $2"