version: 3

# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

paths:
  exclude:
    - ./akka-actor-tests
    - ./akka-actor-typed-tests
    - ./akka-bench-jmh
    - ./akka-persistence-typed-tests
    - ./akka-remote-tests
    - ./akka-stream-tests
    - ./native-image-tests
    - ./samples
