apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node1
  labels:
    app: multi-node-test
spec:
  replicas: 1
  selector:
    matchLabels:
      host: test-node1
  template:
    metadata:
      labels:
        host: test-node1
    spec:
      containers:
      - image: docker.io/andreatp/multi-node-k8s@sha256:e40aa6e73dade152231bc2c0ddbd0bba2136dfd02c991739a236ea41b3f91c18
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - truncate --size -1 /etc/hosts && echo " test-node1" >> /etc/hosts
        imagePullPolicy: Always
        name: multi-test-node1
        volumeMounts:
        - mountPath: /multinode/ssh/keys
          subPath: keys
          name: keys
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: multi-node
          containerPort: 5000
          protocol: TCP
        - name: server-multi
          containerPort: 4711
          protocol: TCP
      volumes:
      - name: keys
        secret:
          secretName: ssh-keys
          defaultMode: 384
          items:
          - key: id_rsa
            path: keys/id_rsa
            mode: 256
          - key: id_rsa.pub
            path: keys/id_rsa.pub
            mode: 256
          - key: authorized_keys
            path: keys/authorized_keys
            mode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: test-node1
  labels:
    app: multi-node-test
spec:
  selector:
    host: test-node1
  ports:
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
    - protocol: TCP
      name: server-multi
      port: 4711
      targetPort: 4711
    - protocol: TCP
      name: multi-node
      port: 5000
      targetPort: 5000
