require 'buildr/scala'
 
repositories.remote << 'http://www.ibiblio.org/maven2'
repositories.remote << 'http://scala-tools.org/repo-releases'
repositories.remote << 'http://scala-tools.org/repo-snapshots'
repositories.remote << 'http://www.lag.net/repo'

desc 'Java utilities for the Akka kernel'
define 'akka-util-java' do
  project.version = '0.1'
  project.group = 'com.scalablesolutions.akka' 
  compile
  package :jar
end

