apiVersion: v1
kind: Service
metadata:
  name: test-node3
  labels:
    app: multi-node-test3
spec:
  selector:
    app: test-node3
  ports:
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
    - protocol: TCP
      name: server-multi
      port: 4711
      targetPort: 4711
    - protocol: TCP
      name: multi-node
      port: 5003
      targetPort: 5003
