apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node2
  labels:
    app: multi-node-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node2
  template:
    metadata:
      labels:
        app: test-node2
    spec:
      containers:
      - image: docker.io/andreatp/multi-node-k8s@sha256:e40aa6e73dade152231bc2c0ddbd0bba2136dfd02c991739a236ea41b3f91c18
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - mkdir /root/.ssh && cp /multinode/ssh/keys/* /root/.ssh
        imagePullPolicy: Always
        name: multi-node-test1
        volumeMounts:
        - mountPath: /multinode/ssh/keys
          subPath: keys
          name: keys
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: multi-node
          containerPort: 5002
          protocol: TCP
        - name: server-multi
          containerPort: 4711
          protocol: TCP
      volumes:
      - name: keys
        secret:
          secretName: ssh-keys
          defaultMode: 384
          items:
          - key: authorized_keys
            path: keys/authorized_keys
            mode: 256
