// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailboxProtocol.proto

package akka.actor.mailbox;

public final class MailboxProtocol {
  private MailboxProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DurableMailboxMessageProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ownerAddress = 1;
    boolean hasOwnerAddress();
    String getOwnerAddress();

    // optional string senderAddress = 2;
    boolean hasSenderAddress();
    String getSenderAddress();

    // optional .UuidProtocol futureUuid = 3;
    boolean hasFutureUuid();
    akka.actor.mailbox.MailboxProtocol.UuidProtocol getFutureUuid();
    akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder getFutureUuidOrBuilder();

    // required bytes message = 4;
    boolean hasMessage();
    com.google.protobuf.ByteString getMessage();
  }
  public static final class DurableMailboxMessageProtocol extends
      com.google.protobuf.GeneratedMessage
      implements DurableMailboxMessageProtocolOrBuilder {
    // Use DurableMailboxMessageProtocol.newBuilder() to construct.
    private DurableMailboxMessageProtocol(Builder builder) {
      super(builder);
    }
    private DurableMailboxMessageProtocol(boolean noInit) {}

    private static final DurableMailboxMessageProtocol defaultInstance;
    public static DurableMailboxMessageProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public DurableMailboxMessageProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return akka.actor.mailbox.MailboxProtocol.internal_static_DurableMailboxMessageProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return akka.actor.mailbox.MailboxProtocol.internal_static_DurableMailboxMessageProtocol_fieldAccessorTable;
    }

    private int bitField0_;
    // required string ownerAddress = 1;
    public static final int OWNERADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object ownerAddress_;
    public boolean hasOwnerAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getOwnerAddress() {
      java.lang.Object ref = ownerAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ownerAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOwnerAddressBytes() {
      java.lang.Object ref = ownerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ownerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string senderAddress = 2;
    public static final int SENDERADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object senderAddress_;
    public boolean hasSenderAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSenderAddress() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          senderAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSenderAddressBytes() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        senderAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .UuidProtocol futureUuid = 3;
    public static final int FUTUREUUID_FIELD_NUMBER = 3;
    private akka.actor.mailbox.MailboxProtocol.UuidProtocol futureUuid_;
    public boolean hasFutureUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public akka.actor.mailbox.MailboxProtocol.UuidProtocol getFutureUuid() {
      return futureUuid_;
    }
    public akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder getFutureUuidOrBuilder() {
      return futureUuid_;
    }

    // required bytes message = 4;
    public static final int MESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private void initFields() {
      ownerAddress_ = "";
      senderAddress_ = "";
      futureUuid_ = akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance();
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOwnerAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFutureUuid()) {
        if (!getFutureUuid().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOwnerAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSenderAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, futureUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOwnerAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSenderAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, futureUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return akka.actor.mailbox.MailboxProtocol.internal_static_DurableMailboxMessageProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return akka.actor.mailbox.MailboxProtocol.internal_static_DurableMailboxMessageProtocol_fieldAccessorTable;
      }

      // Construct using akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFutureUuidFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ownerAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        senderAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (futureUuidBuilder_ == null) {
          futureUuid_ = akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance();
        } else {
          futureUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol.getDescriptor();
      }

      public akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol getDefaultInstanceForType() {
        return akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol.getDefaultInstance();
      }

      public akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol build() {
        akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol buildPartial() {
        akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol result = new akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ownerAddress_ = ownerAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.senderAddress_ = senderAddress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (futureUuidBuilder_ == null) {
          result.futureUuid_ = futureUuid_;
        } else {
          result.futureUuid_ = futureUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol) {
          return mergeFrom((akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol other) {
        if (other == akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol.getDefaultInstance()) return this;
        if (other.hasOwnerAddress()) {
          setOwnerAddress(other.getOwnerAddress());
        }
        if (other.hasSenderAddress()) {
          setSenderAddress(other.getSenderAddress());
        }
        if (other.hasFutureUuid()) {
          mergeFutureUuid(other.getFutureUuid());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOwnerAddress()) {

          return false;
        }
        if (!hasMessage()) {

          return false;
        }
        if (hasFutureUuid()) {
          if (!getFutureUuid().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ownerAddress_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              senderAddress_ = input.readBytes();
              break;
            }
            case 26: {
              akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder subBuilder = akka.actor.mailbox.MailboxProtocol.UuidProtocol.newBuilder();
              if (hasFutureUuid()) {
                subBuilder.mergeFrom(getFutureUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFutureUuid(subBuilder.buildPartial());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required string ownerAddress = 1;
      private java.lang.Object ownerAddress_ = "";
      public boolean hasOwnerAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getOwnerAddress() {
        java.lang.Object ref = ownerAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ownerAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOwnerAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ownerAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ownerAddress_ = getDefaultInstance().getOwnerAddress();
        onChanged();
        return this;
      }
      void setOwnerAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        ownerAddress_ = value;
        onChanged();
      }

      // optional string senderAddress = 2;
      private java.lang.Object senderAddress_ = "";
      public boolean hasSenderAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSenderAddress() {
        java.lang.Object ref = senderAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          senderAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSenderAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        senderAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearSenderAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        senderAddress_ = getDefaultInstance().getSenderAddress();
        onChanged();
        return this;
      }
      void setSenderAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        senderAddress_ = value;
        onChanged();
      }

      // optional .UuidProtocol futureUuid = 3;
      private akka.actor.mailbox.MailboxProtocol.UuidProtocol futureUuid_ = akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          akka.actor.mailbox.MailboxProtocol.UuidProtocol, akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder, akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder> futureUuidBuilder_;
      public boolean hasFutureUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public akka.actor.mailbox.MailboxProtocol.UuidProtocol getFutureUuid() {
        if (futureUuidBuilder_ == null) {
          return futureUuid_;
        } else {
          return futureUuidBuilder_.getMessage();
        }
      }
      public Builder setFutureUuid(akka.actor.mailbox.MailboxProtocol.UuidProtocol value) {
        if (futureUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          futureUuid_ = value;
          onChanged();
        } else {
          futureUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setFutureUuid(
          akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder builderForValue) {
        if (futureUuidBuilder_ == null) {
          futureUuid_ = builderForValue.build();
          onChanged();
        } else {
          futureUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeFutureUuid(akka.actor.mailbox.MailboxProtocol.UuidProtocol value) {
        if (futureUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              futureUuid_ != akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance()) {
            futureUuid_ =
              akka.actor.mailbox.MailboxProtocol.UuidProtocol.newBuilder(futureUuid_).mergeFrom(value).buildPartial();
          } else {
            futureUuid_ = value;
          }
          onChanged();
        } else {
          futureUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearFutureUuid() {
        if (futureUuidBuilder_ == null) {
          futureUuid_ = akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance();
          onChanged();
        } else {
          futureUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder getFutureUuidBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFutureUuidFieldBuilder().getBuilder();
      }
      public akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder getFutureUuidOrBuilder() {
        if (futureUuidBuilder_ != null) {
          return futureUuidBuilder_.getMessageOrBuilder();
        } else {
          return futureUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          akka.actor.mailbox.MailboxProtocol.UuidProtocol, akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder, akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder>
          getFutureUuidFieldBuilder() {
        if (futureUuidBuilder_ == null) {
          futureUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              akka.actor.mailbox.MailboxProtocol.UuidProtocol, akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder, akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder>(
                  futureUuid_,
                  getParentForChildren(),
                  isClean());
          futureUuid_ = null;
        }
        return futureUuidBuilder_;
      }

      // required bytes message = 4;
      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DurableMailboxMessageProtocol)
    }

    static {
      defaultInstance = new DurableMailboxMessageProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DurableMailboxMessageProtocol)
  }

  public interface UuidProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 high = 1;
    boolean hasHigh();
    long getHigh();

    // required uint64 low = 2;
    boolean hasLow();
    long getLow();
  }
  public static final class UuidProtocol extends
      com.google.protobuf.GeneratedMessage
      implements UuidProtocolOrBuilder {
    // Use UuidProtocol.newBuilder() to construct.
    private UuidProtocol(Builder builder) {
      super(builder);
    }
    private UuidProtocol(boolean noInit) {}

    private static final UuidProtocol defaultInstance;
    public static UuidProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public UuidProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return akka.actor.mailbox.MailboxProtocol.internal_static_UuidProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return akka.actor.mailbox.MailboxProtocol.internal_static_UuidProtocol_fieldAccessorTable;
    }

    private int bitField0_;
    // required uint64 high = 1;
    public static final int HIGH_FIELD_NUMBER = 1;
    private long high_;
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getHigh() {
      return high_;
    }

    // required uint64 low = 2;
    public static final int LOW_FIELD_NUMBER = 2;
    private long low_;
    public boolean hasLow() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getLow() {
      return low_;
    }

    private void initFields() {
      high_ = 0L;
      low_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHigh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, high_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, low_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, high_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, low_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static akka.actor.mailbox.MailboxProtocol.UuidProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(akka.actor.mailbox.MailboxProtocol.UuidProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements akka.actor.mailbox.MailboxProtocol.UuidProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return akka.actor.mailbox.MailboxProtocol.internal_static_UuidProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return akka.actor.mailbox.MailboxProtocol.internal_static_UuidProtocol_fieldAccessorTable;
      }

      // Construct using akka.actor.mailbox.MailboxProtocol.UuidProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        high_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        low_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDescriptor();
      }

      public akka.actor.mailbox.MailboxProtocol.UuidProtocol getDefaultInstanceForType() {
        return akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance();
      }

      public akka.actor.mailbox.MailboxProtocol.UuidProtocol build() {
        akka.actor.mailbox.MailboxProtocol.UuidProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private akka.actor.mailbox.MailboxProtocol.UuidProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        akka.actor.mailbox.MailboxProtocol.UuidProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public akka.actor.mailbox.MailboxProtocol.UuidProtocol buildPartial() {
        akka.actor.mailbox.MailboxProtocol.UuidProtocol result = new akka.actor.mailbox.MailboxProtocol.UuidProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.low_ = low_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof akka.actor.mailbox.MailboxProtocol.UuidProtocol) {
          return mergeFrom((akka.actor.mailbox.MailboxProtocol.UuidProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(akka.actor.mailbox.MailboxProtocol.UuidProtocol other) {
        if (other == akka.actor.mailbox.MailboxProtocol.UuidProtocol.getDefaultInstance()) return this;
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHigh()) {

          return false;
        }
        if (!hasLow()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              high_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              low_ = input.readUInt64();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required uint64 high = 1;
      private long high_ ;
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getHigh() {
        return high_;
      }
      public Builder setHigh(long value) {
        bitField0_ |= 0x00000001;
        high_ = value;
        onChanged();
        return this;
      }
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        high_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 low = 2;
      private long low_ ;
      public boolean hasLow() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getLow() {
        return low_;
      }
      public Builder setLow(long value) {
        bitField0_ |= 0x00000002;
        low_ = value;
        onChanged();
        return this;
      }
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        low_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UuidProtocol)
    }

    static {
      defaultInstance = new UuidProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UuidProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DurableMailboxMessageProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DurableMailboxMessageProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UuidProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UuidProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MailboxProtocol.proto\"\200\001\n\035DurableMailb" +
      "oxMessageProtocol\022\024\n\014ownerAddress\030\001 \002(\t\022" +
      "\025\n\rsenderAddress\030\002 \001(\t\022!\n\nfutureUuid\030\003 \001" +
      "(\0132\r.UuidProtocol\022\017\n\007message\030\004 \002(\014\")\n\014Uu" +
      "idProtocol\022\014\n\004high\030\001 \002(\004\022\013\n\003low\030\002 \002(\004B\026\n" +
      "\022akka.actor.mailboxH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DurableMailboxMessageProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DurableMailboxMessageProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DurableMailboxMessageProtocol_descriptor,
              new java.lang.String[] { "OwnerAddress", "SenderAddress", "FutureUuid", "Message", },
              akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol.class,
              akka.actor.mailbox.MailboxProtocol.DurableMailboxMessageProtocol.Builder.class);
          internal_static_UuidProtocol_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_UuidProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UuidProtocol_descriptor,
              new java.lang.String[] { "High", "Low", },
              akka.actor.mailbox.MailboxProtocol.UuidProtocol.class,
              akka.actor.mailbox.MailboxProtocol.UuidProtocol.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
