name: Nightly jdk8/scala2.13
on:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  compile-and-test:
    name: Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8.0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Compile and test for JDK8 (scala2.13)
        run: |-
          # TODO: restore -Dakka.test.multi-node.java=/usr/lib/jvm/jdk8u192-b12/bin/java
          sbt -jvm-opts .jvmopts-ci \
            -Dakka.ci-server=true \
            -Dakka.build.scalaVersion=2.13.3 \
            -Dakka.test.timefactor=1 \
            -Dakka.cluster.assert=on \
            clean compile test doc

      - name: Email on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Nightly jdk8/scala2.13 Failed (Akka)
          to: akka.official@gmail.com
          from: Akka CI (GHActions)
          body: |
            Nightly jdk8/scala2.13 of ${{github.repository}} failed!
            https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
